### ISSUE TITLE
Extended "Edit" button's block on every BIP-created page

### ISSUE THREAD

**Issue by wojciech-sygier** [klucznicy/bip-pages#18]
I'm not entirely sure this is related to the plugin, but it did show up only on the pages created by this plugin, so I am going to report it anyway.

**Browser:** Google Chrome v. 76.0.3809.132 (desktop)
**Type:** UI Bug
**Severity:** Trivial
**Prerequisites:** User is on [this](http://klucznicy.org.pl/bip-test/bip/strona-glowna-bip/) page.
**Steps to reproduce:**
1. Scroll down to the bottom of the page.

**Expected outcome:** "Edit" button's block is just a little bit longer than the text in it
**Actual outcome:** "Edit" button' block extends all the way with the footer with the information about the person that created the page.

**Additional notes:** Also reproducible on every user-created page.

**Media:**
<img width="1440" alt="Zrzut ekranu 2019-09-14 o 16 29 14" src="https://user-images.githubusercontent.com/40696976/64909489-295cb900-d70d-11e9-908a-4d59dc495112.png">

**Comment by lgarczewski** [comment]
This is not related to the plugin. If anything, it's an issue with the skin.
