### ISSUE TITLE
BIP pages cannot be found after deactivating plugin

### ISSUE THREAD

**Issue by ghost** [klucznicy/bip-pages#20]
**Browser:** Google Chrome 77
**Severity:** High
**Prerequisites:** There is at least one BIP page created.
**Steps to reproduce:**
1. Go to "Plugins".
2. Deactivate the "BIP for Wordpress" plugin.
3. Go to "Pages".

**Expected outcome:** All plugin-created pages are found here, they are normal Wordpress pages now.
**Actual outcome:** No plugin-created pages are available, their type did not change.

**Additional notes:** If plugin was not removed, only deactivated, activating it again brings these pages back (they are not deleted)

**Comment by lgarczewski** [comment]
Should be good now. Did basic testing, appears to correctly change post types after de-activation.
