### ISSUE TITLE
BIP main page and user manual won't be created if they are present in trash

### ISSUE THREAD

**Issue by ghost** [klucznicy/bip-pages#21]
**Browser:** Google Chrome 77
**Severity:** Medium
**Prerequisites:** Plugin set up properly.
**Steps to reproduce:**
1. Move BIP main page and user manual page to trash.
2. Turn off and remove the plugin.
3. Install it again.
4. Set it up.
5. Go to BIP pages.

**Expected outcome:** New BIP main page and user manual page were created after reinstalling the plugin.
**Actual outcome:** No new pages were created.

**Additional notes:** Removing old main page and user manual from trash prior to reinstalling the plugin sets these up properly.

**Comment by lgarczewski** [comment]
Nice catch. Thank you! Fixed.
